/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ElIcon: typeof import('element-plus/es')['ElIcon']
  const ElMessage: typeof import('element-plus/es')['ElMessage']
  const ElProgress: typeof import('element-plus/es')['ElProgress']
  const ElUpload: typeof import('element-plus/es')['ElUpload']
}
